name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch (or your default branch)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if using SvelteKit or other JS frameworks)
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Specify Node.js version you want to use

      - name: Install dependencies
        run: npm install # Change if you're using a different package manager

      - name: Build the project
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm run build 

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
